SIGSTKSZ: Definitions have changed in latest glibc
Cast it to size_t so it can be independent of the fact that new glibc
will have this as # define SIGSTKSZ sysconf (_SC_SIGSTKSZ)

failure_signal_handler.cc:139:24: error: no matching function for call to
 'max'
  size_t stack_size = (std::max(SIGSTKSZ, 65536) + page_mask) & ~page_mask;
                       ^~~~~~~~
/mnt/b/yoe/master/build/tmp/work/riscv64-yoe-linux/abseil-cpp/20210324+gitAUTOINC+e1d388e7e7-r0/recipe-sysroot/usr/lib/riscv64-yoe-linux/11.1.0/../../../include/c++/11.1.0/bits/algorithmfw
d.h:407:5: note: candidate template ignored: deduced conflicting types for parameter '_Tp' ('long' vs. 'int')
    max(const _Tp&, const _Tp&);
    ^

Signed-off-by: Khem Raj <raj.khem@gmail.com>